// <auto-generated />
using System;
using EducationPortal.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EducationPortal.Data.Migrations
{
    [DbContext(typeof(PortalDbContext))]
    [Migration("20250827104336_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true);

            modelBuilder.Entity("CourseMaterial", b =>
                {
                    b.Property<int>("CoursesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaterialsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CoursesId", "MaterialsId");

                    b.HasIndex("MaterialsId");

                    b.ToTable("CourseMaterial");
                });

            modelBuilder.Entity("EducationPortal.Data.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Learn the basics of C# programming language, including syntax, data types, and control structures.",
                            Name = "Introduction to C#"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Build modern web applications using ASP.NET Core framework and Entity Framework.",
                            Name = "Web Development with ASP.NET Core"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Master JavaScript basics, DOM manipulation, and modern ES6+ features.",
                            Name = "JavaScript Fundamentals"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Learn database design principles and SQL querying techniques.",
                            Name = "Database Design with SQL"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Build interactive user interfaces with React library and modern JavaScript.",
                            Name = "React for Beginners"
                        });
                });

            modelBuilder.Entity("EducationPortal.Data.Models.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Materials");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("EducationPortal.Data.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "C#"
                        },
                        new
                        {
                            Id = 2,
                            Name = "JavaScript"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Python"
                        },
                        new
                        {
                            Id = 4,
                            Name = "SQL"
                        },
                        new
                        {
                            Id = 5,
                            Name = "HTML/CSS"
                        },
                        new
                        {
                            Id = 6,
                            Name = "React"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Entity Framework"
                        },
                        new
                        {
                            Id = 8,
                            Name = "ASP.NET Core"
                        });
                });

            modelBuilder.Entity("EducationPortal.Data.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "john.doe@email.com",
                            Name = "John",
                            Password = "password123",
                            Phone = "+1234567890",
                            Surname = "Doe"
                        },
                        new
                        {
                            Id = 2,
                            Email = "jane.smith@email.com",
                            Name = "Jane",
                            Password = "password123",
                            Phone = "+1234567891",
                            Surname = "Smith"
                        },
                        new
                        {
                            Id = 3,
                            Email = "bob.johnson@email.com",
                            Name = "Bob",
                            Password = "password123",
                            Phone = "+1234567892",
                            Surname = "Johnson"
                        },
                        new
                        {
                            Id = 4,
                            Email = "alice.brown@email.com",
                            Name = "Alice",
                            Password = "password123",
                            Phone = "+1234567893",
                            Surname = "Brown"
                        },
                        new
                        {
                            Id = 5,
                            Email = "charlie.wilson@email.com",
                            Name = "Charlie",
                            Password = "password123",
                            Phone = "+1234567894",
                            Surname = "Wilson"
                        });
                });

            modelBuilder.Entity("EducationPortal.Data.Models.UserCourse", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompletionPercentage")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("UserCourses");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CourseId = 1,
                            CompletionPercentage = 0
                        },
                        new
                        {
                            UserId = 1,
                            CourseId = 2,
                            CompletionPercentage = 0
                        },
                        new
                        {
                            UserId = 2,
                            CourseId = 1,
                            CompletionPercentage = 0
                        },
                        new
                        {
                            UserId = 2,
                            CourseId = 3,
                            CompletionPercentage = 0
                        },
                        new
                        {
                            UserId = 3,
                            CourseId = 2,
                            CompletionPercentage = 0
                        },
                        new
                        {
                            UserId = 3,
                            CourseId = 4,
                            CompletionPercentage = 0
                        },
                        new
                        {
                            UserId = 4,
                            CourseId = 3,
                            CompletionPercentage = 0
                        },
                        new
                        {
                            UserId = 4,
                            CourseId = 5,
                            CompletionPercentage = 0
                        },
                        new
                        {
                            UserId = 5,
                            CourseId = 1,
                            CompletionPercentage = 0
                        },
                        new
                        {
                            UserId = 5,
                            CourseId = 5,
                            CompletionPercentage = 0
                        });
                });

            modelBuilder.Entity("EducationPortal.Data.Models.UserSkill", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SkillId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SkillLevel")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("UserSkills");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            SkillId = 1,
                            SkillLevel = 0
                        },
                        new
                        {
                            UserId = 1,
                            SkillId = 7,
                            SkillLevel = 0
                        },
                        new
                        {
                            UserId = 2,
                            SkillId = 3,
                            SkillLevel = 0
                        },
                        new
                        {
                            UserId = 2,
                            SkillId = 5,
                            SkillLevel = 0
                        },
                        new
                        {
                            UserId = 3,
                            SkillId = 2,
                            SkillLevel = 0
                        },
                        new
                        {
                            UserId = 3,
                            SkillId = 4,
                            SkillLevel = 0
                        },
                        new
                        {
                            UserId = 4,
                            SkillId = 6,
                            SkillLevel = 0
                        },
                        new
                        {
                            UserId = 4,
                            SkillId = 5,
                            SkillLevel = 0
                        },
                        new
                        {
                            UserId = 5,
                            SkillId = 1,
                            SkillLevel = 0
                        },
                        new
                        {
                            UserId = 5,
                            SkillId = 8,
                            SkillLevel = 0
                        });
                });

            modelBuilder.Entity("EducationPortal.Data.Models.Article", b =>
                {
                    b.HasBaseType("EducationPortal.Data.Models.Material");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("Articles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 7,
                            Title = "Getting Started with Entity Framework",
                            Date = new DateTime(2023, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Resource = "Microsoft Docs"
                        },
                        new
                        {
                            Id = 8,
                            Title = "Best Practices for C# Development",
                            Date = new DateTime(2023, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Resource = "Stack Overflow Blog"
                        },
                        new
                        {
                            Id = 9,
                            Title = "Modern JavaScript Patterns",
                            Date = new DateTime(2023, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Resource = "MDN Web Docs"
                        });
                });

            modelBuilder.Entity("EducationPortal.Data.Models.Book", b =>
                {
                    b.HasBaseType("EducationPortal.Data.Models.Material");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Formant")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PageAmount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PublicationDate")
                        .HasColumnType("TEXT");

                    b.ToTable("Books", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "C# Programming Guide",
                            Author = "Microsoft",
                            Formant = "PDF",
                            PageAmount = 450,
                            PublicationDate = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Title = "Entity Framework Core",
                            Author = "Jon P Smith",
                            Formant = "PDF",
                            PageAmount = 380,
                            PublicationDate = new DateTime(2023, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Title = "JavaScript: The Good Parts",
                            Author = "Douglas Crockford",
                            Formant = "PDF",
                            PageAmount = 172,
                            PublicationDate = new DateTime(2022, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("EducationPortal.Data.Models.Video", b =>
                {
                    b.HasBaseType("EducationPortal.Data.Models.Material");

                    b.Property<int>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quality")
                        .HasColumnType("INTEGER");

                    b.ToTable("Videos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 4,
                            Title = "C# Tutorial for Beginners",
                            Duration = 120,
                            Quality = 1080
                        },
                        new
                        {
                            Id = 5,
                            Title = "ASP.NET Core MVC Tutorial",
                            Duration = 180,
                            Quality = 720
                        },
                        new
                        {
                            Id = 6,
                            Title = "JavaScript ES6 Features",
                            Duration = 90,
                            Quality = 1080
                        });
                });

            modelBuilder.Entity("CourseMaterial", b =>
                {
                    b.HasOne("EducationPortal.Data.Models.Course", null)
                        .WithMany()
                        .HasForeignKey("CoursesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EducationPortal.Data.Models.Material", null)
                        .WithMany()
                        .HasForeignKey("MaterialsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EducationPortal.Data.Models.UserCourse", b =>
                {
                    b.HasOne("EducationPortal.Data.Models.Course", "Course")
                        .WithMany("UserCourses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EducationPortal.Data.Models.User", "User")
                        .WithMany("UserCourses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EducationPortal.Data.Models.UserSkill", b =>
                {
                    b.HasOne("EducationPortal.Data.Models.Skill", "Skill")
                        .WithMany("UserSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EducationPortal.Data.Models.User", "User")
                        .WithMany("UserSkills")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EducationPortal.Data.Models.Article", b =>
                {
                    b.HasOne("EducationPortal.Data.Models.Material", null)
                        .WithOne()
                        .HasForeignKey("EducationPortal.Data.Models.Article", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EducationPortal.Data.Models.Book", b =>
                {
                    b.HasOne("EducationPortal.Data.Models.Material", null)
                        .WithOne()
                        .HasForeignKey("EducationPortal.Data.Models.Book", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EducationPortal.Data.Models.Video", b =>
                {
                    b.HasOne("EducationPortal.Data.Models.Material", null)
                        .WithOne()
                        .HasForeignKey("EducationPortal.Data.Models.Video", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EducationPortal.Data.Models.Course", b =>
                {
                    b.Navigation("UserCourses");
                });

            modelBuilder.Entity("EducationPortal.Data.Models.Skill", b =>
                {
                    b.Navigation("UserSkills");
                });

            modelBuilder.Entity("EducationPortal.Data.Models.User", b =>
                {
                    b.Navigation("UserCourses");

                    b.Navigation("UserSkills");
                });
#pragma warning restore 612, 618
        }
    }
}
